blank_issues_enabled: false
contact_links:
  - name: Ask for help on Discord
    url: https://discord.gg/zzhK54aaYz
    about: Get setup help, troubleshooting advice, and answers to usage questions from the community.
